<a href="https://colab.research.google.com/github/devpatel0005/Stock-Sentiment-Analysis-based-on-News/blob/main/Stock_Sentiment_Analysis_Using_LSTM_based_on_News.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- The data set in consideration is a combination of the world news and stock price shifts available on Kaggle.
- There are 25 columns of top news headlines for each day in the data frame.
Data ranges from 2008 to 2016 and the data from 2000 to 2008 was scrapped from Yahoo finance.
- Labels are based on the Dow Jones Industrial Average stock index.
- Class 1 → the stock price increased.
- Class 0 → the stock price stayed the same or decreased.

In [37]:
import pandas as pd
df=pd.read_csv('/content/Data.csv',encoding='ISO-8859-1')

df.sample(5)

,Date,Label,Top1,Top2,Top3,Top4,Top5,Top6,Top7,Top8,...,Top16,Top17,Top18,Top19,Top20,Top21,Top22,Top23,Top24,Top25
213,2000-11-09,0,From cook to social worker,How charities can benefit from payroll giving,Get tough on racism,Career profile: Health promotion officer,NHS press officer,Test voluntary email,Society briefing test,House improvements,...,Charities need business brains,Last drag for tobacco ads?,US community foundations,The wider role of community foundations,November 8 ratings,Charity of the month (November 2000): grassroo...,Using the Human Rights Act in campaigns,Policing asylum seekers,The cost of asylum,European lobbying lessons for charities
1301,2005-05-06,0,Humphrys vents fury at 'stolen' vote,Trimble's unionists are swept away,How journalists had their say on the Guardian'...,Leading contenders,Loyalist Milburn takes his final bow,This is a low,When to go? The future for Blair and Brown,Labour opens inquest after BNP's surge,...,Press review: Election 2005,Conservative rising stars,Letters: After the poll was over,Letters: War party,First steps on a long journey back,Galloway proclaims his resurrection,SNP bets pay off but bleak night for Plaid Cymru,"From dull campaign to dramatic climax, a tale ...",Geoff Mulgan: Anti-politics,Lynne Jones: The problem for Gordon
1043,2004-04-28,1,Toby Green's top 10 utopias and dystopias,Blair to serve full third term,Murdered tourist's father criticises detective,Corrections and clarifications,"iTunes 4.5 adds iMix, videos, trailers, more",Two new Zires from PalmOne,Hendry storms through to semis,Linux seller licenses Windows Media technology,...,Brown vows to control inflation,Choosing and using an estate agent,Ingram fails in bid to gag Galloway,Universities 'rife with institutional sexism',Big-tent diplomacy for the home,Cycling: Queally in fight to defend his title,US renews attack on Falluja,Battle over south bank skyline begins,The Backbencher: Eye spies,"David Beckham by Sam Taylor-Wood, National Por..."
2405,2009-10-07,0,b'The great energy rip-off in UK: Utility comp...,"b""Piracy: You're doing it wrong""",b'[Classic War Nerd] The French',b'Latvia pushes back against the IMF and EU - ...,"b'Four RCMP officers lied, Polish lawyer tells...","b""For all the recent uproar over Iran's nuclea...",b'Italian MPs to consider ban on full Islamic ...,b'Bahai Cemetery Ruined for the 18th Time',...,b'Sugar becomes the new oil as prices soar: Th...,"b""Obama's paradox: admits Afghanistan war is d...","b'Our data in their hands, nowhere near safe. ...","b""At a demonstration against Guinea's Capt. Mo...",b'UK doctors pay some psychiatric patients to ...,b'Hamas bans Gaza motorcyclists from giving wo...,b'Louvre museum accused of buying stolen arche...,b'Obama administration forces Palestinian Auth...,b'NATO seeks more Russian help in Afghanistan',"b""The plan to de-dollarise the oil market, den..."
254,2001-01-11,1,Walker to woo City by halving Wembley loan,Mexico and Holland are added to Eriksson's Eng...,Transfer system remains in limbo,Ronaldo faces jail over his Nike deal,Knighton sees off fantasy buyer as Carlisle fi...,Dundee delight at date with Diego,Taylor 'quietly confident' of signing £1.75m D...,Quickfire Blackburn almost slip up,...,Gore was a bit of a lefty. No risk of Blair go...,Salmond opts for Westminster in change of heart,Hugo Young: Blair will do nothing to upset big...,Labour to renew poll pledges,Councils' plea to Prescott for floods funding,Salmond opts for Westminster in change of heart,The BBC under fire over quiz show,Sunday Sport publisher criticises Desmond,Express may sue former columnist,Where English can serve but not empower

- ISO-8859-1, also known as Latin-1, is a character encoding standard that maps 256 different characters to numerical values. It's one of the most common encodings used for text in Western European languages

In [4]:
df.shape

(2542, 27)

# Splitting the Data into train and test

In [41]:
df['Date']

0       2000-01-03
1       2000-01-04
2       2000-01-05
3       2000-01-06
4       2000-01-07
           ...
4096    2016-06-27
4097    2016-06-28
4098    2016-06-29
4099    2016-06-30
4100    2016-07-01
Name: Date, Length: 4101, dtype: object

In [42]:
train=df[df['Date']<'20141231']
test=df[df['Date']>'20150101']

In [44]:
train

,Date,Label,Top1,Top2,Top3,Top4,Top5,Top6,Top7,Top8,...,Top16,Top17,Top18,Top19,Top20,Top21,Top22,Top23,Top24,Top25
0,2000-01-03,0,A 'hindrance to operations': extracts from the...,Scorecard,Hughes' instant hit buoys Blues,Jack gets his skates on at ice-cold Alex,Chaos as Maracana builds up for United,Depleted Leicester prevail as Elliott spoils E...,Hungry Spurs sense rich pickings,Gunners so wide of an easy target,...,Flintoff injury piles on woe for England,Hunters threaten Jospin with new battle of the...,Kohl's successor drawn into scandal,The difference between men and women,"Sara Denver, nurse turned solicitor",Diana's landmine crusade put Tories in a panic,Yeltsin's resignation caught opposition flat-f...,Russian roulette,Sold out,Recovering a title
1,2000-01-04,0,Scorecard,The best lake scene,Leader: German sleaze inquiry,"Cheerio, boyo",The main recommendations,Has Cubie killed fees?,Has Cubie killed fees?,Has Cubie killed fees?,...,On the critical list,The timing of their lives,Dear doctor,Irish court halts IRA man's extradition to Nor...,Burundi peace initiative fades after rebels re...,PE points the way forward to the ECB,Campaigners keep up pressure on Nazi war crime...,Jane Ratcliffe,Yet more things you wouldn't know without the ...,Millennium bug fails to bite
2,2000-01-05,0,Coventry caught on counter by Flo,United's rivals on the road to Rio,Thatcher issues defence before trial by video,Police help Smith lay down the law at Everton,Tale of Trautmann bears two more retellings,England on the rack,Pakistan retaliate with call for video of Walsh,Cullinan continues his Cape monopoly,...,South Melbourne (Australia),Necaxa (Mexico),Real Madrid (Spain),Raja Casablanca (Morocco),Corinthians (Brazil),Tony's pet project,Al Nassr (Saudi Arabia),Ideal Holmes show,Pinochet leaves hospital after tests,Useful links
3,2000-01-06,1,Pilgrim knows how to progress,Thatcher facing ban,McIlroy calls for Irish fighting spirit,Leicester bin stadium blueprint,United braced for Mexican wave,"Auntie back in fashion, even if the dress look...",Shoaib appeal goes to the top,Hussain hurt by 'shambles' but lays blame on e...,...,Putin admits Yeltsin quit to give him a head s...,BBC worst hit as digital TV begins to bite,How much can you pay for...,Christmas glitches,"Upending a table, Chopping a line and Scoring ...","Scientific evidence 'unreliable', defence claims",Fusco wins judicial review in extradition case,Rebels thwart Russian advance,Blair orders shake-up of failing NHS,Lessons of law's hard heart
4,2000-01-07,1,Hitches and Horlocks,Beckham off but United survive,Breast cancer screening,Alan Parker,Guardian readers: are you all whingers?,Hollywood Beyond,Ashes and diamonds,Whingers - a formidable minority,...,Most everywhere: UDIs,Most wanted: Chloe lunettes,Return of the cane 'completely off the agenda',From Sleepy Hollow to Greeneland,Blunkett outlines vision for over 11s,"Embattled Dobson attacks 'play now, pay later'...",Doom and the Dome,What is the north-south divide?,Aitken released from jail,Gone aloft
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3718,2014-12-24,1,Death toll among Qatars 2022 World Cup workers...,Fishing Supertrawlers to be banned permanently...,Indian telecommunications company Airtel viola...,North Korea's Internet is down again; second b...,Jakarta to ban virginity tests for female civi...,Workers at Chinese iPhone factories are pressu...,Thousands in Spain protest ban on demonstratio...,London activists occupy 5-storey former bank i...,...,Scientists discover oldest stone tool ever fou...,ISIS claims capture of Jordanian pilot after p...,Russian prime minister warns of 'deep recessio...,Russia says France must fulfil Mistral contrac...,Secret flight linking Israel to the UAE reveal...,Ukraine temporarily cuts off power supplies to...,Coalition plane 'crashes in Syria',Across the world 'Silent Night' to honor WWI X...,Elderly Nigerians Rounded Up And Shot Dead,Russia May Be Cut to Junk rating as S&amp;P Sa...
3719,2014-12-26,1,Saudis are eagerly awaiting the approval of a ...,"Due to the fall in oil prices, Saudi Arabia is...",Bill giving government the power to shutdown t...,A struggle for women's rights is brewing withi...,Putin cancels New Year's Holiday for governmen...,Ireland is siding with Microsoft in its legal ...,More than 80 people including women and childr...,"The Syrian Army has killed nearly 5,000 Islami...",...,Senior UN officials expelled from Sudan follow...,Mauritania journalist sentenced to death for a...,Kim Dotcom Makes Deal with LizardSquad to stop...,Ukraine peace talks called off,Tibetan protests reported in China's Sichuan,New Study Adds to Skepticism Among Security Ex...,"US relocates 3,000 MRAPs, other military gear ...",Russia's new military doctrine names NATO as a...,Protesters in Mexico claim that German arms ma...,A leading Russian elected official on Thursday...
3720,2014-12-29,0,Solar Power Storage Prices Drop 25% In Germany...,North Korea Hit Again By Internet Outage; Expe...,ARCHAEOLOGY - Massive ancient underground city...,Reopen investigation into Westminster pedophil...,"Taliban declare 'defeat' of U.S., allies in Af...",British Falklands defence review after militar...,Virgin Confirms Fault On Plane Circling Over UK,Photo of 'women murdered for refusing sex jiha...,...,"Islamic State executed nearly 2,000 people in ...",The leader of one of Mexico's first anti-crime...,Gmail has been blocked in China,Egyptian writer to face trial for 'insulting I...,Reports reveal scale of destruction of Syrias ...,Russia will supply coal and electricity to Kie...,ISIS executes more doctors in Mosul,Russia shows first sign of recession as GDP co...,"AirAsia plane likely 'at bottom of the sea,' s...",AirAsia Flight's Altitude Request Was Refused
3721,2014-12-30,0,China businessman jailed for 13 years for buyi...,"AirAsia live: Emergency slide, plane door seen...","AirAsia plane wreckage found, bodies being rec...",Scotland confirms case of Ebola - Ebola cases ...,Pope Francis to Catholics: It's time to take a...,Oil hits five-and-a-half-year low below $57 on...,"""Lizard Squad"" members who ruined Christmas fo...",Two students in Thailand face up to 15 years i...,...,Turkey is being used as one of the primary rou...,Swedish mosque set ablaze in second suspected ...,Cybersecurity Firm Identifies Six In Sony Hack...,The U.N. General Assembly voted unanimously Mo...,"""The regime must be destroyed"": Alexei Navalny...","Aleksei Navalny, Russian opposition leader, is...","Search area for Air Asia QZ8501 expanded, stil...",Ebola case confirmed in Glasgow | World news,AirAsia plane carrying 153 people overshoots r...,One of China's most industrialized cities has ...
3722,2014-12-31,0,AirAsia flight found at the bottom of the Java...,North Korean defector details 'human experimen...,Korean Air ex-executive Cho Hyun-ah arrested -...,"South Korean to drop Sony film ""The Interview""...",U.S. opening of oil export widens battle: The ...,FBI agents investigating the Sony Pictures hac...,Indian Government Orders Blocking of 32 Websit...,Russia annual inflation jumps to 11.4% as roub...,...,Newly published NSA documents show agency coul...,Britain says it cannot support new Palestinian...,Bolivias Morales: US 'Backs Drug Trafficking',Euro zone politicians are not obliged to rescu...,Greece Dissolves Parliament to Prepare for Ear...,German Chancellor Angela Merkel in a New Year'...,Al Shabaab leader killed in U.S. air strike in...,New solar power material converts 90 percent o...,China launches website laying claim to Senkaku...,At Least 33 Killed in Yemen Suicide Bombing

# Feature Engineering

In [45]:
data=train.iloc[:,2:27]
data.replace('[^a-zA-Z]',' ',regex=True,inplace=True) #replace the full stop punctuattion with space

#renaming the columns for ease of acess
new_index=[str(i) for i in range(25)] #since our data has 25 columns top 25 news headlines for stock
data.columns=new_index

In [46]:
data

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,A hindrance to operations extracts from the...,Scorecard,Hughes instant hit buoys Blues,Jack gets his skates on at ice cold Alex,Chaos as Maracana builds up for United,Depleted Leicester prevail as Elliott spoils E...,Hungry Spurs sense rich pickings,Gunners so wide of an easy target,Derby raise a glass to Strupar s debut double,Southgate strikes Leeds pay the penalty,...,Flintoff injury piles on woe for England,Hunters threaten Jospin with new battle of the...,Kohl s successor drawn into scandal,The difference between men and women,Sara Denver nurse turned solicitor,Diana s landmine crusade put Tories in a panic,Yeltsin s resignation caught opposition flat f...,Russian roulette,Sold out,Recovering a title
1,Scorecard,The best lake scene,Leader German sleaze inquiry,Cheerio boyo,The main recommendations,Has Cubie killed fees,Has Cubie killed fees,Has Cubie killed fees,Hopkins furious at Foster s lack of Hannibal...,Has Cubie killed fees,...,On the critical list,The timing of their lives,Dear doctor,Irish court halts IRA man s extradition to Nor...,Burundi peace initiative fades after rebels re...,PE points the way forward to the ECB,Campaigners keep up pressure on Nazi war crime...,Jane Ratcliffe,Yet more things you wouldn t know without the ...,Millennium bug fails to bite
2,Coventry caught on counter by Flo,United s rivals on the road to Rio,Thatcher issues defence before trial by video,Police help Smith lay down the law at Everton,Tale of Trautmann bears two more retellings,England on the rack,Pakistan retaliate with call for video of Walsh,Cullinan continues his Cape monopoly,McGrath puts India out of their misery,Blair Witch bandwagon rolls on,...,South Melbourne Australia,Necaxa Mexico,Real Madrid Spain,Raja Casablanca Morocco,Corinthians Brazil,Tony s pet project,Al Nassr Saudi Arabia,Ideal Holmes show,Pinochet leaves hospital after tests,Useful links
3,Pilgrim knows how to progress,Thatcher facing ban,McIlroy calls for Irish fighting spirit,Leicester bin stadium blueprint,United braced for Mexican wave,Auntie back in fashion even if the dress look...,Shoaib appeal goes to the top,Hussain hurt by shambles but lays blame on e...,England s decade of disasters,Revenge is sweet for jubilant Cronje,...,Putin admits Yeltsin quit to give him a head s...,BBC worst hit as digital TV begins to bite,How much can you pay for,Christmas glitches,Upending a table Chopping a line and Scoring ...,Scientific evidence unreliable defence claims,Fusco wins judicial review in extradition case,Rebels thwart Russian advance,Blair orders shake up of failing NHS,Lessons of law s hard heart
4,Hitches and Horlocks,Beckham off but United survive,Breast cancer screening,Alan Parker,Guardian readers are you all whingers,Hollywood Beyond,Ashes and diamonds,Whingers a formidable minority,Alan Parker part two,Thuggery Toxins and Ties,...,Most everywhere UDIs,Most wanted Chloe lunettes,Return of the cane completely off the agenda,From Sleepy Hollow to Greeneland,Blunkett outlines vision for over s,Embattled Dobson attacks play now pay later ...,Doom and the Dome,What is the north south divide,Aitken released from jail,Gone aloft
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3718,Death toll among Qatars World Cup workers...,Fishing Supertrawlers to be banned permanently...,Indian telecommunications company Airtel viola...,North Korea s Internet is down again second b...,Jakarta to ban virginity tests for female civi...,Workers at Chinese iPhone factories are pressu...,Thousands in Spain protest ban on demonstratio...,London activists occupy storey former bank i...,Russian Inflation Passes Indicates Pricin...,Australia records biggest emissions drop in a ...,...,Scientists discover oldest stone tool ever fou...,ISIS claims capture of Jordanian pilot after p...,Russian prime minister warns of deep recessio...,Russia says France must fulfil Mistral contrac...,Secret flight linking Israel to the UAE reveal...,Ukraine temporarily cuts off power supplies to...,Coalition plane crashes in Syria,Across the world Silent Night to honor WWI X...,Elderly Nigerians Rounded Up And Shot Dead,Russia May Be Cut to Junk rating as S amp P Sa...
3719,Saudis are eagerly awaiting the approval of a ...,Due to the fall in oil prices Saudi Arabia is...,Bill giving government the power to shutdown t...,A struggle for women s rights is brewing withi...,Putin cancels New Year s Holiday for governmen...,Ireland is siding with Microsoft in its legal ...,More than people including women and childr...,The Syrian Army has killed nearly Islami...,ISIS governor of Mosul killed in airstrikes,Court clears way for clinically dead pregnant ...,...,Senior UN officials expelled from Sudan follow...,Mauritania journalist sentenced to death for a...,Kim Dotcom Makes Deal with LizardSquad to stop...,Ukraine peace talks called off,Tibetan protests reported in China s Sichuan,New Study Adds to Skepticism Among Security Ex...,US relocates MRAPs other military gear ...,Russia s new military doctrine names NATO as a...,Protesters in Mexico claim that German arms ma...,A leading Russian elected official on Thursday...
3720,Solar Power Storage Prices Drop In Germany...,North Korea Hit Again By Internet Outage Expe...,ARCHAEOLOGY Massive ancient underground city...,Reopen investigation into Westminster pedophil...,Taliban declare defeat of U S allies in Af...,British Falklands defence review after militar...,Virgin Confirms Fault On Plane Circling Over UK,Photo of women murdered for refusing sex jiha...,The German chancellor s office has fallen vict...,Thirty seven children whose parents were kille...,...,Islamic State executed nearly people in ...,The leader of one of Mexico s first anti crime...,Gmail has been blocked in China,Egyptian writer to face trial for insulting I...,Reports reveal scale of destruction of Syrias ...,Russia will supply coal and electricity to Kie...,ISIS executes more doctors in Mosul,Russia shows first sign of recession as GDP co...,AirAsia plane likely at bottom of the sea s...,AirAsia Flight s Altitude Request Was Refused
3721,China businessman jailed for years for buyi...,AirAsia live Emergency slide plane door seen...,AirAsia plane wreckage found bodies being rec...,Scotland confirms case of Ebola Ebola cases ...,Pope Francis to Catholics It s time to take a...,Oil hits five and a half year low below on...,Lizard Squad members who ruined Christmas fo...,Two students in Thailand face up to years i...,New Research Blames Insiders Not North Korea f...,Russian ruble drops percent as economy shrinks,...,Turkey is being used as one of the primary rou...,Swedish mosque set ablaze in second suspected ...,Cybersecurity Firm Identifies Six In Sony Hack...,The U N General Assembly voted unanimously Mo...,The regime must be destroyed Alexei Navalny...,Aleksei Navalny Russian opposition leader is...,Search area for Air Asia QZ expanded stil...,Ebola case confirmed in Glasgow World news,AirAsia plane carrying people overshoots r...,One of China s most industrialized cities has ...
3722,AirAsia flight found at the bottom of the Java...,North Korean defector details human experimen...,Korean Air ex executive Cho Hyun ah arrested ...,South Korean to drop Sony film The Interview ...,U S opening of oil export widens battle The ...,FBI agents investigating the Sony Pictures hac...,Indian Government Orders Blocking of Websit...,Russia annual inflation jumps to as roub...,WikiLeaks claims employees Google mail metada...,Militant mistakenly broadcasts his location,...,Newly published NSA documents show agency coul...,Britain says it cannot support new Palestinian...,Bolivias Morales US Backs Drug Trafficking,Euro zone politicians are not obliged to rescu...,Greece Dissolves Parliament to Prepare for Ear...,German Chancellor Angela Merkel in a New Year ...,Al Shabaab leader killed in U S air strike in...,New solar power material converts percent o...,China launches website laying claim to Senkaku...,At Least Killed in Yemen Suicide Bombing

# Converting the headlines into lowercase

In [47]:
for index in new_index:
  data[index]=data[index].str.lower()

In [48]:
data.head()

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,a hindrance to operations extracts from the...,scorecard,hughes instant hit buoys blues,jack gets his skates on at ice cold alex,chaos as maracana builds up for united,depleted leicester prevail as elliott spoils e...,hungry spurs sense rich pickings,gunners so wide of an easy target,derby raise a glass to strupar s debut double,southgate strikes leeds pay the penalty,...,flintoff injury piles on woe for england,hunters threaten jospin with new battle of the...,kohl s successor drawn into scandal,the difference between men and women,sara denver nurse turned solicitor,diana s landmine crusade put tories in a panic,yeltsin s resignation caught opposition flat f...,russian roulette,sold out,recovering a title
1,scorecard,the best lake scene,leader german sleaze inquiry,cheerio boyo,the main recommendations,has cubie killed fees,has cubie killed fees,has cubie killed fees,hopkins furious at foster s lack of hannibal...,has cubie killed fees,...,on the critical list,the timing of their lives,dear doctor,irish court halts ira man s extradition to nor...,burundi peace initiative fades after rebels re...,pe points the way forward to the ecb,campaigners keep up pressure on nazi war crime...,jane ratcliffe,yet more things you wouldn t know without the ...,millennium bug fails to bite
2,coventry caught on counter by flo,united s rivals on the road to rio,thatcher issues defence before trial by video,police help smith lay down the law at everton,tale of trautmann bears two more retellings,england on the rack,pakistan retaliate with call for video of walsh,cullinan continues his cape monopoly,mcgrath puts india out of their misery,blair witch bandwagon rolls on,...,south melbourne australia,necaxa mexico,real madrid spain,raja casablanca morocco,corinthians brazil,tony s pet project,al nassr saudi arabia,ideal holmes show,pinochet leaves hospital after tests,useful links
3,pilgrim knows how to progress,thatcher facing ban,mcilroy calls for irish fighting spirit,leicester bin stadium blueprint,united braced for mexican wave,auntie back in fashion even if the dress look...,shoaib appeal goes to the top,hussain hurt by shambles but lays blame on e...,england s decade of disasters,revenge is sweet for jubilant cronje,...,putin admits yeltsin quit to give him a head s...,bbc worst hit as digital tv begins to bite,how much can you pay for,christmas glitches,upending a table chopping a line and scoring ...,scientific evidence unreliable defence claims,fusco wins judicial review in extradition case,rebels thwart russian advance,blair orders shake up of failing nhs,lessons of law s hard heart
4,hitches and horlocks,beckham off but united survive,breast cancer screening,alan parker,guardian readers are you all whingers,hollywood beyond,ashes and diamonds,whingers a formidable minority,alan parker part two,thuggery toxins and ties,...,most everywhere udis,most wanted chloe lunettes,return of the cane completely off the agenda,from sleepy hollow to greeneland,blunkett outlines vision for over s,embattled dobson attacks play now pay later ...,doom and the dome,what is the north south divide,aitken released from jail,gone aloft

- Now for implementing the NLP techniques like Bag of Words or Tf-IDF we need to combine these all columns of a row into one single paragraph for every row

In [49]:
data.index

Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
       ...
       3713, 3714, 3715, 3716, 3717, 3718, 3719, 3720, 3721, 3722],
      dtype='int64', length=3723)

In [50]:
headlines=[]
for rows in range(0,len(data.index)):
  headlines.append(' '.join(str(x) for x in data.iloc[rows,0:25])) # columns are from 0 to 24 so we mentioned 0:25 to include all

In [51]:
headlines[1]

'scorecard the best lake scene leader  german sleaze inquiry cheerio  boyo the main recommendations has cubie killed fees  has cubie killed fees  has cubie killed fees  hopkins  furious  at foster s lack of hannibal appetite has cubie killed fees  a tale of two tails i say what i like and i like what i say elbows  eyes and nipples task force to assess risk of asteroid collision how i found myself at last on the critical list the timing of their lives dear doctor irish court halts ira man s extradition to northern ireland burundi peace initiative fades after rebels reject mandela as mediator pe points the way forward to the ecb campaigners keep up pressure on nazi war crimes suspect jane ratcliffe yet more things you wouldn t know without the movies millennium bug fails to bite'

- Now for every row we have merged  of each and every index the news into one single headline

In [52]:
!pip install gensim

Requirement already satisfied: gensim in /usr/local/lib/python3.12/dist-packages (4.4.0)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.5.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.1.1)

In [53]:
import nltk
from gensim.models import Word2Vec
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

In [54]:
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [55]:
"""
lematized_headlines=[]
for paragraph in headlines:
  sentences=nltk.sent_tokenize(paragraph)
  for i in range(len(sentences)):
    text=[word for word in sentences[i] if word not in stopwords.words('english') ]
    text=' '.join(text)
  lematized_headlines.append(text)
"""

"\nlematized_headlines=[]\nfor paragraph in headlines:\n  sentences=nltk.sent_tokenize(paragraph)\n  for i in range(len(sentences)):\n    text=[word for word in sentences[i] if word not in stopwords.words('english') ]\n    text=' '.join(text)\n  lematized_headlines.append(text)\n"

In [56]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
training_data=tfidf.fit_transform(headlines).toarray()

In [57]:
training_data.shape

(3723, 44486)

- Now preparing test data

In [60]:
test_transform=[]
for row in range(0,len(test.index)):
    test_transform.append(' '.join(str(x) for x in test.iloc[row,2:27]))
test_data=tfidf.transform(test_transform).toarray()

In [61]:
test_data.shape

(126, 44486)

In [62]:
from sklearn.ensemble import RandomForestClassifier

# Initialize the RandomForestClassifier model
# Using n_estimators=200 for a robust model, you can adjust this parameter.
randomforest_classifier = RandomForestClassifier(n_estimators=200, criterion='entropy')

# Train the classifiers
randomforest_classifier.fit(training_data, train['Label'])

RandomForestClassifier(criterion='entropy', n_estimators=200)

In [63]:
predictions = randomforest_classifier.predict(test_data)

In [64]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Get true labels for the test set
y_true = test['Label']

# Evaluate the model
print("Classification Report:")
print(classification_report(y_true, predictions))

print("Confusion Matrix:")
print(confusion_matrix(y_true, predictions))

print("Accuracy Score:")
print(accuracy_score(y_true, predictions))

Classification Report:
              precision    recall  f1-score   support

           0       0.17      0.04      0.06        56
           1       0.53      0.86      0.65        70

    accuracy                           0.49       126
   macro avg       0.35      0.45      0.36       126
weighted avg       0.37      0.49      0.39       126

Confusion Matrix:
[[ 2 54]
 [10 60]]
Accuracy Score:
0.49206349206349204

In [65]:
training_data

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [66]:
test_data

array([[0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       ...,
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.1427859, 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ]])

# LSTM Implementation

In [69]:
import tensorflow
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Embedding,Dropout,BatchNormalization,LSTM

In [76]:
model=Sequential()
model.add(Dense(10,activation='relu',input_shape=(training_data.shape[1],)))
model.add(tensorflow.keras.layers.Reshape((1, 10))) # Reshape to (batch_size, timesteps, features)
model.add(LSTM(10))
model.add(Dense(1,activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [77]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 10)             │       444,870 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ reshape (Reshape)               │ (None, 1, 10)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_5 (LSTM)                   │ (None, 10)             │           840 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │            11 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 445,721 (1.70 MB)

 Trainable params: 445,721 (1.70 MB)

 Non-trainable params: 0 (0.00 B)

In [78]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [81]:
history=model.fit(training_data,epochs=10,validation_data=test_data,batch_size=32)

Epoch 1/10

ValueError: None values not supported.

In [80]:
import matplotlib.pyplot as plt